/* tslint:disable */
/* eslint-disable */
/**
 * Indexer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { XSwapHop } from './XSwapHop';
import {
    XSwapHopFromJSON,
    XSwapHopFromJSONTyped,
    XSwapHopToJSON,
} from './XSwapHop';

/**
 * 
 * @export
 * @interface ApiV1WormholeXswapPost200ResponseRoutesInner
 */
export interface ApiV1WormholeXswapPost200ResponseRoutesInner {
    /**
     * final token amount will be received
     * @type {string}
     * @memberof ApiV1WormholeXswapPost200ResponseRoutesInner
     */
    amount: string;
    /**
     * paths
     * @type {Array<XSwapHop>}
     * @memberof ApiV1WormholeXswapPost200ResponseRoutesInner
     */
    hops?: Array<XSwapHop>;
}

/**
 * Check if a given object implements the ApiV1WormholeXswapPost200ResponseRoutesInner interface.
 */
export function instanceOfApiV1WormholeXswapPost200ResponseRoutesInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "amount" in value;

    return isInstance;
}

export function ApiV1WormholeXswapPost200ResponseRoutesInnerFromJSON(json: any): ApiV1WormholeXswapPost200ResponseRoutesInner {
    return ApiV1WormholeXswapPost200ResponseRoutesInnerFromJSONTyped(json, false);
}

export function ApiV1WormholeXswapPost200ResponseRoutesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1WormholeXswapPost200ResponseRoutesInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'hops': !exists(json, 'hops') ? undefined : ((json['hops'] as Array<any>).map(XSwapHopFromJSON)),
    };
}

export function ApiV1WormholeXswapPost200ResponseRoutesInnerToJSON(value?: ApiV1WormholeXswapPost200ResponseRoutesInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'hops': value.hops === undefined ? undefined : ((value.hops as Array<any>).map(XSwapHopToJSON)),
    };
}

