/* tslint:disable */
/* eslint-disable */
/**
 * Indexer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1TransactionsSyncPost200Response
 */
export interface ApiV1TransactionsSyncPost200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiV1TransactionsSyncPost200Response
     */
    msg: string;
}

/**
 * Check if a given object implements the ApiV1TransactionsSyncPost200Response interface.
 */
export function instanceOfApiV1TransactionsSyncPost200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "msg" in value;

    return isInstance;
}

export function ApiV1TransactionsSyncPost200ResponseFromJSON(json: any): ApiV1TransactionsSyncPost200Response {
    return ApiV1TransactionsSyncPost200ResponseFromJSONTyped(json, false);
}

export function ApiV1TransactionsSyncPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1TransactionsSyncPost200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'msg': json['msg'],
    };
}

export function ApiV1TransactionsSyncPost200ResponseToJSON(value?: ApiV1TransactionsSyncPost200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'msg': value.msg,
    };
}

