/* tslint:disable */
/* eslint-disable */
/**
 * Indexer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ApiV1WormholeXswapPost200ResponseRoutesInner } from './ApiV1WormholeXswapPost200ResponseRoutesInner';
import {
    ApiV1WormholeXswapPost200ResponseRoutesInnerFromJSON,
    ApiV1WormholeXswapPost200ResponseRoutesInnerFromJSONTyped,
    ApiV1WormholeXswapPost200ResponseRoutesInnerToJSON,
} from './ApiV1WormholeXswapPost200ResponseRoutesInner';

/**
 * 
 * @export
 * @interface ApiV1WormholeXswapPost200Response
 */
export interface ApiV1WormholeXswapPost200Response {
    /**
     * 
     * @type {Array<ApiV1WormholeXswapPost200ResponseRoutesInner>}
     * @memberof ApiV1WormholeXswapPost200Response
     */
    routes: Array<ApiV1WormholeXswapPost200ResponseRoutesInner>;
}

/**
 * Check if a given object implements the ApiV1WormholeXswapPost200Response interface.
 */
export function instanceOfApiV1WormholeXswapPost200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "routes" in value;

    return isInstance;
}

export function ApiV1WormholeXswapPost200ResponseFromJSON(json: any): ApiV1WormholeXswapPost200Response {
    return ApiV1WormholeXswapPost200ResponseFromJSONTyped(json, false);
}

export function ApiV1WormholeXswapPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1WormholeXswapPost200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'routes': ((json['routes'] as Array<any>).map(ApiV1WormholeXswapPost200ResponseRoutesInnerFromJSON)),
    };
}

export function ApiV1WormholeXswapPost200ResponseToJSON(value?: ApiV1WormholeXswapPost200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'routes': ((value.routes as Array<any>).map(ApiV1WormholeXswapPost200ResponseRoutesInnerToJSON)),
    };
}

