/* tslint:disable */
/* eslint-disable */
/**
 * Indexer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenState
 */
export interface TokenState {
    /**
     * ChainId
     * @type {number}
     * @memberof TokenState
     */
    chain: number;
    /**
     * token addr
     * @type {string}
     * @memberof TokenState
     */
    address: string;
    /**
     * bigint wei
     * @type {string}
     * @memberof TokenState
     */
    amount: string;
}

/**
 * Check if a given object implements the TokenState interface.
 */
export function instanceOfTokenState(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "chain" in value;
    isInstance = isInstance && "address" in value;
    isInstance = isInstance && "amount" in value;

    return isInstance;
}

export function TokenStateFromJSON(json: any): TokenState {
    return TokenStateFromJSONTyped(json, false);
}

export function TokenStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenState {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'chain': json['chain'],
        'address': json['address'],
        'amount': json['amount'],
    };
}

export function TokenStateToJSON(value?: TokenState | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'chain': value.chain,
        'address': value.address,
        'amount': value.amount,
    };
}

